name: Build Trava JDK 8 DCEVM

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment variables
      run: |
        echo "SOURCE_JDK_BRANCH=dcevm8u282b08" >> $GITHUB_ENV
        echo "SOURCE_JDK_TAG=dcevm8u282b08" >> $GITHUB_ENV
        echo "HSWAP_AGENT_DOWNLOAD_URL=https://github.com/HotswapProjects/HotswapAgent/releases/download/RELEASE-1.4.1/hotswap-agent-1.4.1.jar" >> $GITHUB_ENV

    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install cygwin
        choco install vs2010sdk
        choco install wget
        C:\tools\cygwin\cygwinsetup.exe -q -P make,unzip,automake,autoconf,zip
        git config --system core.longpaths true
        git config --global core.autocrlf false

    - name: Clone openjdk-build repository
      run: |
        git clone --depth 1 --branch travaopenjdk https://github.com/TravaOpenJDK/openjdk-build.git

    - name: Build (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        C:\tools\cygwin\bin\bash.exe -c './build_windows.sh'

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: builds
        path: openjdk-build/workspace/target/*
